name: TimeCycle
options:
  bundleIdPrefix: com.timecycle
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: true

targets:

  # ==================== iOS App ====================
  TimeCycle:
    type: application
    platform: iOS
    sources:
      - path: TimeCycle
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timecycle.app
        INFOPLIST_FILE: TimeCycle/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: true
    entitlements:
      path: TimeCycle/TimeCycle.entitlements
    # dependencies:
    #   - target: TimeCycleWatch Watch App

  # ==================== watchOS App ====================
  TimeCycleWatch Watch App:
    type: application
    platform: watchOS
    sources:
      - path: TimeCycleWatch
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timecycle.app.watchkitapp
        INFOPLIST_FILE: TimeCycleWatch/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SDKROOT: watchos
